# Configuration file for Calamares
# Syntax is YAML 1.2
---
modules-search: [ local, /usr/lib/calamares/modules ]

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary

- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - grubcfg
  - bootloader
  - packages
  - plymouthcfg
  - initramfscfg
  - initramfs
  - umount

- show:
  - finished

branding: nonla
prompt-install: false
dont-chroot: false
